name: Deploy backend to Azure Container Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry (ACR)
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and Push Docker Image (backend)
        run: |
          cd springboot-backend
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/my-backend:latest ./springboot-backend
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/my-backend:latest

      - name: Deploy backend to Azure Container Apps
        run: |


          # Deploy or update the container app
          az containerapp up \
            --name "${{ secrets.CONTAINER_APP_NAME_AUTO_BACKEND }}" \
            --resource-group "${{ secrets.RESOURCE_GROUP }}" \
            --environment "${{ secrets.CONTAINERAPPS_ENVIRONMENT }}" \
            --image "${{ secrets.ACR_NAME }}.azurecr.io/my-backend:latest" \
            --ingress external \
            --target-port 8080 \
